services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 192.168.3.11
    environment:
      GITLAB_OMNIBUS_CONFIG: 
        external_url 'http://192.168.3.11'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        # 如果配置了 SMTP 邮件发送，可以在这里添加
    ports:
      - 5580:80
      - 5443:443
      - 2222:22
    volumes:
      - /opt/gitlab/config:/etc/gitlab
      - /opt/gitlab/logs:/var/log/gitlab
      - /opt/gitlab/data:/var/opt/gitlab
    shm_size: 256m

